---
- name: Setup Visual Studio Code
  vars:
    is_remove: false

    apt_key_path: /etc/apt/keyrings/packages.microsoft.asc
    apt_repository: deb [arch=amd64,arm64,armhf signed-by={{ apt_key_path }}] https://packages.microsoft.com/repos/code stable main

  block:
    - name: Setup Visual Studio Code > Install Prerequisite
      become: true
      ansible.builtin.apt:
        name:
          - apt-transport-https
        state: present

    - name: Setup Visual Studio Code > Setup Install
      when: not is_remove
      block:
        - name: Setup Visual Studio Code > Get APT Key
          become: true
          ansible.builtin.get_url:
            url: https://packages.microsoft.com/keys/microsoft.asc
            dest: "{{ apt_key_path }}"
            mode: '0644'

        - name: Setup Visual Studio Code > Add Repository
          become: true
          ansible.builtin.apt_repository:
            repo: "{{ apt_repository }}"
            filename: vscode
            state: present

        - name: Setup Visual Studio Code > Install package
          become: true
          ansible.builtin.apt:
            name: code
            state: present

        - name: Setup Visual Studio Code > Get code executable
          ansible.builtin.command: which code
          register: code
          changed_when: false
          ignore_errors: true

        - name: Setup Visual Studio Code > Setup Config
          ansible.builtin.import_tasks: ./config.yml
          vars:
            code_executable: "{{ code.stdout }}"

    - name: Setup Visual Studio Code > Setup Remove
      when: is_remove
      block:
        - name: Setup Visual Studio Code > Get code executable
          ansible.builtin.command: which code
          register: code
          changed_when: false
          ignore_errors: true

        - name: Setup Visual Studio Code > Setup Config
          ansible.builtin.import_tasks: ./config.yml
          vars:
            code_executable: "{{ code.stdout }}"

        - name: Setup Visual Studio Code > Remove package
          become: true
          ansible.builtin.apt:
            name: code
            state: absent

        - name: Setup Visual Studio Code > Remove Repository
          become: true
          ansible.builtin.apt_repository:
            repo: "{{ apt_repository }}"
            filename: vscode
            state: absent

        - name: Setup Visual Studio Code > Remove APT Key
          become: true
          ansible.builtin.file:
            path: "{{ apt_key_path }}"
            state: absent
