---
- name: Setup ripgrep
  become: true
  vars:
    is_remove: false
    ripgrep_url: https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep_14.1.0-1_amd64.deb
    ripgrep_name: ripgrep

  block:
    - name: Setup ripgrep > Setup Install
      when: not is_remove
      block:
        - name: Setup ripgrep > Install packages
          ansible.builtin.apt:
            deb: "{{ ripgrep_url }}"
            state: present

    - name: Setup ripgrep > Setup Remove
      when: is_remove
      block:
        - name: Setup ripgrep > Remove packages
          ansible.builtin.apt:
            name: "{{ ripgrep_name }}"
            state: absent
