---
- name: Setup apt packages
  become: true
  vars:
    is_remove: false

    pkgs:
      - htop
      - age
      - curl
      - wget
      - apt-transport-https

  block:
    - name: Setup apt packages > Setup Install
      when: not is_remove
      block:
        - name: Setup apt packages > Install packages
          ansible.builtin.apt:
            name: "{{ pkgs }}"
            state: present

    - name: Setup apt packages > Setup Remove
      when: is_remove
      block:
        - name: Setup apt packages > Remove packages
          ansible.builtin.apt:
            name: "{{ pkgs }}"
            state: absent
