---
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:

  - name: install requirements
    command: ansible-galaxy collection install community.general
    register: req
    changed_when: '"Nothing to do" not in req.stdout'

  tasks:
    - name: ensure flathub repo existed
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        state: present

    - name: flatpak apps
      community.general.flatpak:
        name:
          - com.getpostman.Postman
          - com.redis.RedisInsight
          - com.slack.Slack
