# code: language=ansible
---
- name: Install Flatpak Apps
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Install requirements
      ansible.builtin.command: ansible-galaxy collection install community.general
      register: req
      changed_when: '"Nothing to do" not in req.stdout'

  tasks:
    - name: Ensure flathub repo existed
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        state: present

    - name: Install apps
      community.general.flatpak:
        name:
          - com.getpostman.Postman
          - com.redis.RedisInsight
          - com.slack.Slack
