# this playbook is used to generate new ssh keys
# if looking for load ssh keys from sops, see ./ssh-sops.yml

# code: language=ansible
---
- name: Generate SSH key-pairs
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Install requirements
      ansible.builtin.command: ansible-galaxy collection install community.general
      register: req
      changed_when: '"Nothing to do" not in req.stdout'

  tasks:
    - name: Load global config
      ansible.builtin.set_fact:
        global_config: "{{ lookup('file', playbook_dir + '/../../config.json') | from_json }}"

    - name: Load config
      ansible.builtin.set_fact:
        dir: "{{ global_config['ssh']['dir_path'] }}"
        keys: "{{ global_config['ssh']['keys'] }}"

    - name: Make directory
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
        mode: "0755"

    - name: Create key pairs
      community.crypto.openssh_keypair:
        path: "{{ dir }}/id_ed25519_{{ item.name }}"
        type: ed25519
        state: present
        force: false
      with_items: "{{ keys }}"

    # ? SKIP, use ssh in home-manager to generate config or use ./ssh-sops.yml
    - name: Make config
      community.general.ssh_config:
        host: "{{ item.host }}"
        hostname: "{{ item.host }}"
        identity_file: "{{ dir }}/id_ed25519_{{ item.name }}"
        ssh_config_file: "{{ dir }}/config"
      with_items: "{{ keys }}"

    - name: Config replace /home/<user>
      ansible.builtin.replace:
        path: "{{ dir }}/config"
        regexp: \/home\/[^\/]+
        replace: "~"
