# this playbook is used to generate new ssh keys
# if looking for load ssh keys from sops, see ./ssh-sops.yml

---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    title_prefix: SSH
    dir: ~/.ssh
    keys:
      - host: github.com
        hostname: github.com
        file: id_ed25519_github
      - host: gitlab.com
        hostname: gitlab.com
        file: id_ed25519_gitlab
      - host: phabricator.sirclo.com
        hostname: phabricator.sirclo.com
        file: id_ed25519_phabricator

  pre_tasks:
    - name: "{{ title_prefix }} > install requirements"
      command: ansible-galaxy collection install community.general
      register: req
      changed_when: '"Nothing to do" not in req.stdout'

  tasks:
    - name: "{{ title_prefix }} > make dir"
      file:
        path: "{{ dir }}"
        state: directory

    - name: "{{ title_prefix }} > create keys"
      openssh_keypair:
        path: "{{ dir }}/{{ item.file }}"
        type: ed25519
        state: present
        force: no
      with_items: "{{ keys }}"

    # # ? SKIP, use ssh in home-manager to generate config or use ./ssh-sops.yml
    # - name: "{{ title_prefix }} > make config"
    #   community.general.ssh_config:
    #     host: "{{ item.host }}"
    #     hostname: "{{ item.hostname }}"
    #     identity_file: "{{ dir }}/{{ item.file }}"
    #     ssh_config_file: "{{ dir }}/config"
    #   with_items: "{{ keys }}"

    # - name: "{{ title_prefix }} > config replace /home/<user>"
    #   ansible.builtin.replace:
    #     path: "{{ dir }}/config"
    #     regexp: '\/home\/[^\/]+'
    #     replace: '~'
