---
- name: Setup sops
  become: true
  vars:
    is_remove: false

    version: v3.9.0
    url: https://github.com/getsops/sops/releases/download/{{ version }}/sops-{{ version }}.linux.amd64
    executable: /usr/local/bin/sops

  block:
    - name: Setup sops > Setup Install
      when: not is_remove
      block:
        - name: Setup sops > Download from URL
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: "{{ executable }}"
            mode: '0755'

    - name: Setup sops > Setup Remove
      when: is_remove
      block:
        - name: Setup sops > Remove
          ansible.builtin.file:
            path: "{{ executable }}"
            state: absent
