# for installation, refer to <root_project>/ansible/tasks/dev/python/pipx-packages.yml
---
- name: Ansible galaxy > Pre Setup
  # when: ansible_host == "127.0.0.1" and ansible_connection == "local"
  delegate_to: localhost
  vars:
    ansible_collections:
      - community.general
      - community.sops
      - community.crypto
  block:
    - name: Ansible galaxy > check executable path
      ansible.builtin.command: which ansible-galaxy
      register: ansible_galaxy
      ignore_errors: true
      changed_when: false

    - name: Ansible galaxy > Install prerequisite
      when: ansible_galaxy.rc == 0
      ansible.builtin.command: "{{ ansible_galaxy.stdout }} collection install {{ ansible_collections | join(' ') }}"
      register: res
      changed_when: '"Nothing to do" not in res.stdout'
