---
- name: Setup Brave Browser
  become: true
  vars:
    is_remove: false

    apt_key_url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    apt_key_path: /etc/apt/keyrings/brave-browser-archive-keyring.gpg
    apt_repository: deb [signed-by={{ apt_key_path }}] https://brave-browser-apt-release.s3.brave.com/ stable main
    apt_repository_filename: brave-browser-release

  block:
    - name: Install Prerequisite
      ansible.builtin.apt:
        name:
          - apt-transport-https
        state: present

    - name: Setup Install
      when: not is_remove
      block:
        - name: Get APT Key
          ansible.builtin.get_url:
            url: "{{ apt_key_url }}"
            dest: "{{ apt_key_path }}"
            mode: "0644"

        - name: Add Repository
          ansible.builtin.apt_repository:
            repo: "{{ apt_repository }}"
            filename: "{{ apt_repository_filename }}"
            state: present

        - name: Install package
          ansible.builtin.apt:
            name: brave-browser
            state: present

    - name: Setup Remove
      when: is_remove
      block:
        - name: Remove package
          ansible.builtin.apt:
            name: brave-browser
            state: absent

        - name: Remove Repository
          ansible.builtin.apt_repository:
            repo: "{{ apt_repository }}"
            filename: "{{ apt_repository_filename }}"
            state: absent

        - name: Remove APT Key
          ansible.builtin.file:
            path: "{{ apt_key_path }}"
            state: absent
