---
- name: Setup mise
  vars:
    is_remove: false

    tmp_dir: "{{ ansible_env.HOME }}/tmp"
    script_path: "{{ tmp_dir }}/mise.sh"
    mise_executable: "{{ ansible_env.HOME }}/.local/bin/mise"

  block:
    - name: Ensure tmp directory
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: directory
        mode: '0755'

    - name: Setup Install
      when: not is_remove
      block:
        - name: Download installation script
          ansible.builtin.get_url:
            url: https://mise.run
            dest: "{{ script_path }}"
            mode: 'u+x'

        - name: Execute script
          ansible.builtin.command: "{{ script_path }}"
          args:
            creates: "{{ mise_executable }}"

    - name: Setup Remove
      when: is_remove
      block:
        - name: Remove
          ansible.builtin.command: "{{ mise_executable }} implode --quiet --yes"
          args:
            removes: "{{ mise_executable }}"
