---
- name: Add text to shell
  block:
    - name: Text in shell > Check shell file exists
      ansible.builtin.stat:
        path: "{{ shell_file }}"
      register: current_file

    - name: "Text in shell > into {{ shell_file + ' with state: ' + state }}"
      when: current_file.stat.exists
      ansible.builtin.blockinfile:
        path: "{{ shell_file }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ shell_indicator }}"
        block: "{{ text }}"
        state: "{{ state }}"
