# this playbook is used to generate new ssh keys
# if looking for load ssh keys from sops, see ./sops.yml

---
- name: SSH generate key-pairs
  vars:
    is_remove: false
  block:
    - name: SSH generate key-pairs > Load global config
      ansible.builtin.set_fact:
        global_config: "{{ lookup('file', playbook_dir + '/../../config/global.json') | from_json }}"

    - name: SSH generate key-pairs > Load config
      ansible.builtin.set_fact:
        dir: "{{ global_config['ssh']['dir_path'] }}"
        keys: "{{ global_config['ssh']['keys'] }}"

    - name: SSH generate key-pairs > Setup Create SSH Keys
      when: not is_remove
      block:
        - name: SSH generate key-pairs > Make directory
          ansible.builtin.file:
            path: "{{ dir }}"
            state: directory
            mode: "0755"

        - name: SSH generate key-pairs > Create key pairs
          community.crypto.openssh_keypair:
            path: "{{ dir }}/id_ed25519_{{ item.name }}"
            type: ed25519
            state: present
            force: false
          with_items: "{{ keys }}"

        # ? SKIP, use ssh in home-manager to generate config or use ./ssh-sops.yml
        - name: SSH generate key-pairs > Make config
          community.general.ssh_config:
            host: "{{ item.host }}"
            hostname: "{{ item.host }}"
            identity_file: "{{ dir }}/id_ed25519_{{ item.name }}"
            ssh_config_file: "{{ dir }}/config"
          with_items: "{{ keys }}"

        - name: SSH generate key-pairs > Config replace /home/<user>
          ansible.builtin.replace:
            path: "{{ dir }}/config"
            regexp: \/home\/[^\/]+
            replace: "~"

    - name: SSH generate key-pairs > Setup Remove
      when: is_remove
      block:
        - name: SSH generate key-pairs > Remove config
          ansible.builtin.file:
            path: "{{ dir }}/config"
            state: absent

        - name: SSH generate key-pairs > Remove public keys
          ansible.builtin.file:
            path: "{{ dir }}/id_ed25519_{{ item.name }}.pub"
            state: absent
          with_items: "{{ keys }}"

        - name: SSH generate key-pairs > Remove private keys
          ansible.builtin.file:
            path: "{{ dir }}/id_ed25519_{{ item.name }}"
            state: absent
          with_items: "{{ keys }}"
