---
- name: Install Go programming language
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    go_version: "1.22.5"
    go_download_url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
    go_extract_path: "/usr/local"
    go_install_dir: "/usr/local/go"
    go_bin_path: "{{ go_install_dir }}/bin"
    shell_rc_file: "~/.zshrc"

  tasks:
    - name: Check if it is already installed
      stat:
        path: "{{ go_bin_path }}/go"
      register: go_installed

    - name: Install Go
      become: true
      when: not go_installed.stat.exists
      block:
      - name: Download
        get_url:
          url: "{{ go_download_url }}"
          dest: "/tmp/{{ go_tarball }}"

      - name: Remove existing installation
        command: "rm -rf {{ go_install_dir }}"

      - name: Extract tarball
        ansible.builtin.unarchive:
          src: "/tmp/{{ go_tarball }}"
          dest: "{{ go_extract_path }}"
          creates: "{{ go_bin_path }}/go"

    - name: Add bin directory to PATH
      blockinfile:
        path: "{{ shell_rc_file }}"
        block: |
          # Add Go bin directory to PATH
          if [ -d "{{ go_bin_path }}" ] ; then
            export PATH="$PATH:{{ go_bin_path }}"
          fi
