---
- name: Setup oh my zsh
  hosts: localhost
  connection: local
  vars:
    is_remove: false
    is_reset_when_remove: true

    tmp_path: ~/tmp
    script_url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    script_path: "{{ tmp_path }}/ohmyzsh-install.sh"
    installed_path: ~/.oh-my-zsh

    shell_file: ~/.zshrc

  tasks:
    - name: Setup Install
      when: not is_remove
      block:
        - name: Create tmp directory
          ansible.builtin.file:
            path: "{{ tmp_path }}"
            state: directory
            mode: '0755'

        - name: Download installation script
          ansible.builtin.get_url:
            url: "{{ script_url }}"
            dest: "{{ script_path }}"
            mode: 'u+x'

        - name: Execute script
          ansible.builtin.command: "{{ script_path }}"
          args:
            creates: "{{ installed_path }}"

        - name: Install plugins
          block:
            - name: Plugin get zsh-autosuggestions
              ansible.builtin.git:
                repo: https://github.com/zsh-users/zsh-autosuggestions
                dest: "{{ installed_path }}/custom/plugins/zsh-autosuggestions"
                version: a411ef3e0992d4839f0732ebeb9823024afaaaa8

            - name: Plugin get zsh-syntax-highlighting
              ansible.builtin.git:
                repo: https://github.com/zsh-users/zsh-syntax-highlighting
                dest: "{{ installed_path }}/custom/plugins/zsh-syntax-highlighting"
                version: db085e4661f6aafd24e5acb5b2e17e4dd5dddf3e

            - name: Update plugin
              ansible.builtin.replace:
                path: "{{ shell_file }}"
                regexp: 'plugins=\(([^)]*)\)'
                replace: 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting)'

    - name: Setup Remove
      when: is_remove
      block:
        - name: Bash
          ansible.builtin.command: which bash
          register: bash
          changed_when: false

        - name: Remove
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              echo y | sh {{ installed_path }}/tools/uninstall.sh
            executable: "{{ bash.stdout }}"
          args:
            removes: "{{ installed_path }}"

        - name: Make it plain .zshrc
          when: is_reset_when_remove
          ansible.builtin.copy:
            dest: "{{ shell_file }}"
            content: ""
            mode: '0644'
            force: true
