---
- name: Setup sops
  hosts: localhost
  connection: local
  become: true
  vars:
    is_remove: true

    version: v3.9.0
    url: https://github.com/getsops/sops/releases/download/{{ version }}/sops-{{ version }}.linux.amd64
    path: /usr/local/bin/sops

  tasks:
    - name: Setup Install
      when: not is_remove
      block:
        - name: Download from URL
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: "{{ path }}"
            mode: '0755'

    - name: Setup Remove
      when: is_remove
      block:
        - name: Remove
          ansible.builtin.file:
            path: "{{ path }}"
            state: absent
