---
- name: Setup NPM
  vars:
    # when this task imported, and parent has same vars
    # parent's variable will be used
    is_remove: false

    global_dirname: .npm-global
    global_dir: "{{ ansible_env.HOME }}/{{ global_dirname }}"
    global_packages:
      - name: pnpm
        state: present

    shell_indicator: "NPM"
    shell_bin_path: |
      if [ -d "{{ ansible_env.HOME }}/{{ global_dirname }}/bin" ] ; then
        PATH="{{ ansible_env.HOME }}/{{ global_dirname }}/bin:$PATH"
      fi

  block:
    - name: Setup NPM > Check NPM executable path
      ansible.builtin.stat:
        path: "{{ npm_executable }}"
      register: npm

    - name: Setup NPM > NPM executable exists
      when: npm.stat.exists
      block:
        - name: Setup NPM > Setup Install
          when: not is_remove
          block:
            - name: Setup NPM > Make global package dir
              ansible.builtin.file:
                path: "{{ global_dir }}"
                state: directory
                mode: "0755"

            - name: Setup NPM > Configure npm global dir
              ansible.builtin.command: "npm config set prefix {{ global_dir }}"
              changed_when: false

            - name: Setup NPM > Add PATH
              ansible.builtin.include_tasks: "{{ workdir }}/ansible/tasks/shell/add-text/setup.yml"
              vars:
                text: "{{ shell_bin_path }}"

            - name: Setup NPM > Install Global Packages
              community.general.npm:
                name: "{{ item.name }}"
                global: true
                state: "{{ item.state }}"
              with_items: "{{ global_packages }}"

        - name: Setup NPM > Setup Remove
          when: is_remove
          block:
            - name: Setup NPM > Remove Global Packages
              community.general.npm:
                name: "{{ item }}"
                global: true
                state: absent
              with_items: "{{ global_packages }}"

            - name: Setup NPM > Remove PATH
              ansible.builtin.include_tasks: "{{ workdir }}/ansible/tasks/shell/add-text/setup.yml"
              vars:
                text: "{{ shell_bin_path }}"

            - name: Setup NPM > Remove global package dir
              ansible.builtin.file:
                path: "{{ global_dir }}"
                state: absent
