# see https://github.com/nodesource/distributions
---
- name: Setup Node.js
  vars:
    is_remove: false

    version: '22.x'
    script_url: "https://deb.nodesource.com/setup_{{ version }}"
    script_path: "/tmp/nodesource_setup.sh"

    apt_repository_path: /etc/apt/sources.list.d/nodesource.list
    apt_key_path: /usr/share/keyrings/nodesource.gpg

  block:
    - name: Setup Node.js > Setup Install
      when: not is_remove
      block:
        - name: Setup Node.js > Download installation script
          become: true
          ansible.builtin.get_url:
            url: "{{ script_url }}"
            dest: "{{ script_path }}"
            mode: '0755'

        - name: Setup Node.js > Execute script
          become: true
          ansible.builtin.command: "{{ script_path }}"
          args:
            creates: "{{ apt_repository_path }}"

        - name: Setup Node.js > Install package
          become: true
          ansible.builtin.apt:
            name: nodejs
            state: present

        - name: Setup Node.js > Check npm exists
          ansible.builtin.command: which npm
          register: npm
          changed_when: false
          ignore_errors: true

        - name: Setup Node.js > Setup NPM
          ansible.builtin.import_tasks: ./npm-packages.yml
          vars:
            npm_executable: "{{ npm.stdout }}"

    - name: Setup Node.js > Setup Remove
      when: is_remove
      block:
        - name: Setup Node.js > Check npm exists
          ansible.builtin.command: which npm
          register: npm
          changed_when: false
          ignore_errors: true

        - name: Setup Node.js > Setup NPM
          ansible.builtin.import_tasks: ./npm-packages.yml
          vars:
            npm_executable: "{{ npm.stdout }}"

        - name: Setup Node.js > Remove package
          become: true
          ansible.builtin.apt:
            name: nodejs
            state: absent

        - name: Setup Node.js > Remove Repository
          become: true
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          with_items:
            - "{{ apt_repository_path }}"
            - "{{ apt_key_path }}"
