# this playbook to run any task dynamically based on `task_file` variable
# use case: testing, run individual task_file, delete pkg, etc
# example:
# ansible-playbook ansible/playbooks/_handler.yml -e '{"task_file": "../tasks/dev/mise/setup-common.yml", "is_remove": true}' -K
---
- name: Handler
  hosts: "{{ _hosts | default('debian') }}"
  vars:
    is_remove: false
  tasks:

    - name: Get project root path
      ansible.builtin.command: "git rev-parse --show-toplevel"
      register: root_project
      delegate_to: localhost
      changed_when: false

    - name: Setup
      vars:
        workdir: "{{ root_project.stdout }}"
      block:
        - name: Pre ansible galaxy
          ansible.builtin.include_tasks: "{{ workdir }}/ansible/tasks/tools/ansible/pre-galaxy.yml"

        - name: Run Tasks
          ansible.builtin.include_tasks: "{{ workdir }}/{{ task_file | default('ansible/tasks/hello.yml') }}"
