---
- name: Setup Debian
  hosts: "{{ _hosts | default('debian') }}"
  connection: "{{ _connection | default('ssh') }}"
  vars:
    is_remove: false

    task_files:
      - ../tasks/pkg/apt.yml

      - ../tasks/pkg/flatpak/setup-debian.yml

      - ../tasks/dev/go/setup-common.yml
      - ../tasks/dev/nodejs/setup-debian.yml

      - ../tasks/tools/sops/setup-common.yml
      - ../tasks/tools/neovim/setup-common.yml

      - ../tasks/container/podman/setup-debian.yml

      - ../tasks/ui/vscode/setup-debian.yml
      - ../tasks/ui/brave/setup-debian.yml

      - ../tasks/auth/ssh/sops.yml

      - ../tasks/fonts/setup-common.yml

    # ! do remove this task in debian, remove operation will revoke ssh access
    only_install_task_files:
      - ../tasks/shell/zsh/setup-debian.yml
      - ../tasks/tools/openssh-server/setup-debian.yml

  tasks:
    - name: Setup Install
      when: not is_remove
      block:
        - name: Run Install Tasks
          ansible.builtin.include_tasks: "{{ task_file }}"
          loop: "{{ task_files }}"
          loop_control:
            loop_var: task_file

        - name: Run Only Install Tasks
          ansible.builtin.include_tasks: "{{ task_file }}"
          loop: "{{ only_install_task_files }}"
          loop_control:
            loop_var: task_file

    - name: Setup Remove
      when: is_remove
      block:
        - name: Run Remove Tasks
          ansible.builtin.include_tasks: "{{ task_file }}"
          loop: "{{ task_files | reverse | list }}"
          loop_control:
            loop_var: task_file
