---
- name: Setup Debian
  hosts: "{{ _hosts | default('debian') }}"
  connection: "{{ _connection | default('ssh') }}"
  vars:
    is_remove: false

    task_files:
      # shells
      - ../tasks/shell/zsh/setup-debian.yml

      # dev
      - ../tasks/dev/go/setup-common.yml
      - ../tasks/dev/nodejs/setup-debian.yml

      # pkg
      - ../tasks/pkg/apt.yml
      - ../tasks/pkg/flatpak/setup-debian.yml

      # tools
      - ../tasks/tools/sops/setup-common.yml
      - ../tasks/tools/neovim/setup-common.yml
      - ../tasks/tools/openssh-server/setup-debian.yml


      # container
      - ../tasks/container/podman/setup-debian.yml

      # GUI apps
      - ../tasks/ui/vscode/setup-debian.yml
      - ../tasks/ui/brave/setup-debian.yml

      # auth
      - ../tasks/auth/ssh/sops.yml

      # fonts
      - ../tasks/fonts/setup-common.yml

  tasks:
    - name: Run Tasks
      ansible.builtin.include_tasks: "{{ task_file }}"
      loop: "{{ task_files }}"
      loop_control:
        loop_var: task_file
