# for flatpak apps, it can be seen in common module (../common)
---
- name: Setup Flatpak
  hosts: localhost
  connection: local
  become: true
  vars:
    is_remove: false

    repositories:
      - name: flathub
        url: https://dl.flathub.org/repo/flathub.flatpakrepo

  pre_tasks:
    - name: Check ansible-galaxy exists
      ansible.builtin.command: which ansible-galaxy
      register: ansible_galaxy
      ignore_errors: true
      changed_when: false

    - name: Install requirements
      when: ansible_galaxy.rc == 0
      ansible.builtin.command: ansible-galaxy collection install community.general
      register: req
      changed_when: '"Nothing to do" not in req.stdout'

  tasks:
    - name: Setup Install
      when: not is_remove
      block:
        - name: Install package
          ansible.builtin.apt:
            name: flatpak
            state: present

        - name: Add repositories
          community.general.flatpak_remote:
            name: "{{ item.name }}"
            flatpakrepo_url: "{{ item.url }}"
            state: present
          with_items: "{{ repositories }}"

    - name: Setup Remove
      when: is_remove
      block:
        - name: Remove repositories
          community.general.flatpak_remote:
            name: "{{ item.name }}"
            flatpakrepo_url: "{{ item.url }}"
            state: absent
          with_items: "{{ repositories }}"

        - name: Remove package
          ansible.builtin.apt:
            name: flatpak
            state: absent
