---
- name: Setup podman
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    is_remove: false

    pkgs: 
      - podman
      - podman-compose
    
    shell_file: "~/.zshrc"
    shell_marker: "# {mark} ANSIBLE MANAGED BLOCK: PODMAN"
    shell_alias: |
      if command -v podman &> /dev/null; then
        alias docker="podman"
      fi
      if command -v podman-compose &> /dev/null; then
        alias docker-compose="podman-compose"
      fi

  tasks:
    - name: Setup Install 
      when: not is_remove
      block:
      - name: Install Packages
        become: true
        ansible.builtin.apt:
          pkg: "{{ pkgs }}"
          state: present
      - name: Add Alias
        ansible.builtin.blockinfile:
          marker: "{{ shell_marker }}"
          path: "{{ shell_file }}"
          block: "{{ shell_alias }}"
          state: present 
    
    - name: Setup Remove
      when: is_remove
      block:
      - name: Remove Alias
        ansible.builtin.blockinfile:
          marker: "{{ shell_marker }}"
          path: "{{ shell_file }}"
          block: "{{ shell_alias }}"
          state: absent 
      - name: Remove Packages
        become: true
        ansible.builtin.apt:
          pkg: "{{ pkgs }}"
          state: absent