---
- name: Setup Flatpak Apps
  vars:
    is_remove: false

    repositories:
      - name: flathub
        url: https://dl.flathub.org/repo/flathub.flatpakrepo

    apps:
      - com.getpostman.Postman
      - com.redis.RedisInsight
      - com.slack.Slack

  block:
    - name: Setup Flatpak Apps > Ensure repositories
      community.general.flatpak_remote:
        name: "{{ item.name }}"
        flatpakrepo_url: "{{ item.url }}"
        state: present
      with_items: "{{ repositories }}"

    - name: Setup Flatpak Apps > Setup Install
      when: not is_remove
      block:
        - name: Setup Flatpak Apps > Install
          community.general.flatpak:
            name: "{{ apps }}"
            state: present

    - name: Setup Flatpak Apps > Setup Remove
      when: is_remove
      block:
        - name: Setup Flatpak Apps > Remove
          community.general.flatpak:
            name: "{{ apps }}"
            state: absent
