---
- name: Setup Flatpak Apps
  vars:
    is_remove: false

    repositories:
      - name: flathub
        url: https://dl.flathub.org/repo/flathub.flatpakrepo

    apps:
      - com.getpostman.Postman
      - com.redis.RedisInsight
      - com.slack.Slack

  block:
    - name: Pre Setup (run ansible against localhost)
      when: ansible_host == "127.0.0.1" and ansible_connection == "local"
      block:
        - name: Check ansible-galaxy exists
          ansible.builtin.command: which ansible-galaxy
          register: ansible_galaxy
          ignore_errors: true
          changed_when: false

        - name: Install requirements
          when: ansible_galaxy.rc == 0
          ansible.builtin.command: ansible-galaxy collection install community.general
          register: req
          changed_when: '"Nothing to do" not in req.stdout'

    - name: Ensure repositories
      community.general.flatpak_remote:
        name: "{{ item.name }}"
        flatpakrepo_url: "{{ item.url }}"
        state: present
      with_items: "{{ repositories }}"

    - name: Setup Install
      when: not is_remove
      block:
        - name: Install
          community.general.flatpak:
            name: "{{ apps }}"
            state: present

    - name: Setup Remove
      when: is_remove
      block:
        - name: Remove
          community.general.flatpak:
            name: "{{ apps }}"
            state: absent
