# for flatpak apps, it can be seen in common module (../common)
---
- name: Setup Flatpak
  vars:
    is_remove: false

    repositories:
      - name: flathub
        url: https://dl.flathub.org/repo/flathub.flatpakrepo

  block:
    - name: Setup Flatpak > Setup Install
      when: not is_remove
      block:
        - name: Setup Flatpak > Install package
          become: true
          ansible.builtin.apt:
            name: flatpak
            state: present

        - name: Setup Flatpak > Add repositories
          community.general.flatpak_remote:
            name: "{{ item.name }}"
            flatpakrepo_url: "{{ item.url }}"
            state: present
          with_items: "{{ repositories }}"

    - name: Setup Flatpak > Setup Remove
      when: is_remove
      block:
        - name: Setup Flatpak > Remove repositories
          when: false # skip for now due to stuck
          community.general.flatpak_remote:
            name: "{{ item.name }}"
            state: absent
          with_items: "{{ repositories }}"

        - name: Setup Flatpak > Remove package
          become: true
          ansible.builtin.apt:
            name: flatpak
            state: absent
