---
- name: Setup openssh server
  become: true
  vars:
    is_remove: false

    pkgs:
      - openssh-server

  block:
    - name: Setup openssh server > Setup Install
      when: not is_remove
      block:
        - name: Setup openssh server > Install packages
          ansible.builtin.apt:
            name: "{{ pkgs }}"
            state: present

    - name: Setup openssh server > Setup Remove
      when: is_remove
      block:
        - name: Setup openssh server > Remove packages
          ansible.builtin.apt:
            name: "{{ pkgs }}"
            state: absent
