---
- name: Setup Go Programming Language
  vars:
    is_remove: false

    go_version: "1.22.5"
    go_download_url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
    go_extract_dir: "/usr/local"
    go_install_dir: "/usr/local/go"
    go_bin_dir: "{{ go_install_dir }}/bin"

    shell_indicator: "GO"
    shell_bin_path: |
      if [ -d "{{ go_bin_dir }}" ] ; then
        export PATH="$PATH:{{ go_bin_dir }}"
      fi

  block:
    - name: Setup Install
      when: not is_remove
      block:
        - name: Check if it is already installed
          ansible.builtin.stat:
            path: "{{ go_bin_dir }}/go"
          register: go_installed

        - name: Install
          become: true
          when: not go_installed.stat.exists
          block:
            - name: Download
              ansible.builtin.get_url:
                url: "{{ go_download_url }}"
                dest: "/tmp/{{ go_tarball }}"
                mode: "0644"

            - name: Extract to binary path
              ansible.builtin.unarchive:
                src: "/tmp/{{ go_tarball }}"
                dest: "{{ go_extract_dir }}"
                creates: "{{ go_bin_dir }}/go"
                remote_src: true

        - name: Add PATH
          ansible.builtin.import_tasks: "{{ workdir }}/ansible/tasks/shell/add-text/setup.yml"
          vars:
            text: "{{ shell_bin_path }}"
            with_system: true

        - name: Setup Packages
          ansible.builtin.import_tasks: ./packages.yml
          vars:
            go_executable: "{{ go_bin_dir }}/go"

    - name: Setup Remove
      when: is_remove
      block:
        - name: Setup Packages
          ansible.builtin.import_tasks: ./packages.yml
          vars:
            go_executable: "{{ go_bin_dir }}/go"

        - name: Remove PATH
          ansible.builtin.import_tasks: "{{ workdir }}/ansible/tasks/shell/add-text/setup.yml"
          vars:
            text: "{{ shell_bin_path }}"
            with_system: true

        - name: Remove installation dir
          become: true
          ansible.builtin.file:
            path: "{{ go_install_dir }}"
            state: absent
