---
- name: Setup zsh
  vars:
    is_remove: false

    pkgs:
      - zsh
  block:
    - name: Setup zsh > Setup Install
      when: not is_remove
      block:
        - name: Setup zsh > install package
          become: true
          ansible.builtin.apt:
            name: "{{ pkgs }}"
            state: present

        - name: Setup zsh > Setup oh my zsh
          ansible.builtin.import_tasks: ./ohmyzsh.yml

    - name: Setup zsh > Setup Remove
      when: is_remove
      block:
        - name: Setup zsh > Setup oh my zsh
          ansible.builtin.import_tasks: ./ohmyzsh.yml

        - name: Setup zsh > remove package
          become: true
          ansible.builtin.apt:
            name: "{{ pkgs }}"
            state: absent
