---
- name: Setup neovim
  vars:
    is_remove: false

    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    tmp_path: /tmp/nvim-linux64.tar.gz
    install_path: /opt
    bin_path: "{{ install_path }}/nvim-linux64"

    shell_indicator: "NEOVIM"
    shell_bin_path: |
      if [ -d "{{ bin_path }}/bin" ] ; then
        export PATH="$PATH:{{ bin_path }}/bin"
      fi

  block:
    - name: Setup neovim > Setup Install
      when: not is_remove
      block:
        - name: Setup neovim > Download from URL
          become: true
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: "{{ tmp_path }}"
            mode: '0755'

        - name: Setup neovim > Extract tarball
          become: true
          ansible.builtin.unarchive:
            src: "{{ tmp_path }}"
            dest: "{{ install_path }}"
            remote_src: true

        - name: Setup neovim > Add PATH
          ansible.builtin.include_tasks: "{{ workdir }}/ansible/tasks/shell/add-text/setup.yml"
          vars:
            text: "{{ shell_bin_path }}"
            with_system: true

    - name: Setup neovim > Setup Remove
      when: is_remove
      block:
        - name: Setup neovim > Remove PATH
          ansible.builtin.include_tasks: "{{ workdir }}/ansible/tasks/shell/add-text/setup.yml"
          vars:
            text: "{{ shell_bin_path }}"
            with_system: true

        - name: Setup neovim > Remove
          become: true
          ansible.builtin.file:
            path: "{{ bin_path }}"
            state: absent
