---
- name: Setup podman
  vars:
    is_remove: false

    # in debian, podman need separate podman-compose (due to old pkg)
    pkgs: "{{ ['podman', 'podman-compose'] if ansible_distribution == 'Debian' else ['podman'] }}"

    shell_indicator: "PODMAN"
    shell_alias: |
      if command -v podman &> /dev/null; then
        alias docker="podman"
      fi
      if command -v podman-compose &> /dev/null; then
        alias docker-compose="podman-compose"
      fi

  block:
    - name: Setup podman > Setup Install
      when: not is_remove
      block:
        - name: Setup podman > Install Packages
          become: true
          ansible.builtin.apt:
            pkg: "{{ pkgs }}"
            state: present

        - name: Setup podman > Add Alias
          ansible.builtin.include_tasks: "{{ workdir }}/ansible/tasks/shell/add-text/setup.yml"
          vars:
            text: "{{ shell_alias }}"
            with_system: true

    - name: Setup podman > Setup Remove
      when: is_remove
      block:
        - name: Setup podman > Remove Alias
          ansible.builtin.include_tasks: "{{ workdir }}/ansible/tasks/shell/add-text/setup.yml"
          vars:
            text: "{{ shell_alias }}"
            with_system: true

        - name: Setup podman > Remove Packages
          become: true
          ansible.builtin.apt:
            pkg: "{{ pkgs }}"
            state: absent
