---
- name: Setup podman
  vars:
    is_remove: false

    pkgs:
      - podman
      - podman-compose

    shell_indicator: "PODMAN"
    shell_alias: |
      if command -v podman &> /dev/null; then
        alias docker="podman"
      fi
      if command -v podman-compose &> /dev/null; then
        alias docker-compose="podman-compose"
      fi

  block:
    - name: Setup Install
      when: not is_remove
      block:
        - name: Install Packages
          become: true
          ansible.builtin.apt:
            pkg: "{{ pkgs }}"
            state: present

        - name: Add Alias
          ansible.builtin.import_tasks: "{{ workdir }}/ansible/tasks/shell/add-text/setup.yml"
          vars:
            text: "{{ shell_alias }}"
            with_system: true

    - name: Setup Remove
      when: is_remove
      block:
        - name: Remove Alias
          ansible.builtin.import_tasks: "{{ workdir }}/ansible/tasks/shell/add-text/setup.yml"
          vars:
            text: "{{ shell_alias }}"
            with_system: true

        - name: Remove Packages
          become: true
          ansible.builtin.apt:
            pkg: "{{ pkgs }}"
            state: absent
