# see https://github.com/nodesource/distributions
---
- name: Setup Python
  vars:
    is_remove: false

    python_only_install_pkgs:
      # debian system depends on python3
      # removing this possibly break the system
      - python3

    python_pkgs:
      - python3-pip
      - virtualenv
      - pipx

  block:
    - name: Setup Python > Setup Install
      when: not is_remove
      block:
        - name: Setup Python > Install packages
          become: true
          ansible.builtin.apt:
            name: "{{ python_only_install_pkgs + python_pkgs }}"
            state: present

        - name: Setup Python > Check pipx executable exists
          ansible.builtin.command: which pipx
          register: python_pipx
          changed_when: false

        - name: Setup Python > setup pipx
          ansible.builtin.include_tasks: ./pipx-packages.yml
          vars:
            pipx_executable: "{{ python_pipx.stdout }}"

        - name: Setup Python > Check pip executable exists
          ansible.builtin.command: which pip
          register: python_pip
          changed_when: false

        - name: Setup Python > setup pip
          ansible.builtin.include_tasks: ./pip-packages.yml
          vars:
            pip_executable: "{{ python_pip.stdout }}"

    - name: Setup Python > Setup Remove
      when: is_remove
      block:
        - name: Setup Python > Check pip executable exists
          ansible.builtin.command: which pip
          register: python_pip
          changed_when: false

        - name: Setup Python > setup pip
          ansible.builtin.include_tasks: ./pip-packages.yml
          vars:
            pip_executable: "{{ python_pip.stdout }}"

        - name: Setup Python > Check pipx executable exists
          ansible.builtin.command: which pipx
          register: python_pipx
          changed_when: false

        - name: Setup Python > setup pipx
          ansible.builtin.include_tasks: ./pipx-packages.yml
          vars:
            pipx_executable: "{{ python_pipx.stdout }}"

        - name: Setup Python > Remove packages
          become: true
          ansible.builtin.apt:
            name: "{{ python_pkgs }}"
            state: absent

    - name: Setup scrcpy > remove unnecessary deps
      become: true
      ansible.builtin.apt:
        autoremove: true
